# Site
url: "https://jaewoopk.github.io"
baseurl: ""
repository: "jaewoopk/jaewoopk.github.io"
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 박재우
title: Server Developer (Finance IT)
email: jaewoopk000@naver.com
website: https://github.com/jaewoopk

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  jaewoopk

# Additional icon links
additional_links:
  - title: Blog (Tistory)
    icon: fas fa-blog
    url: "https://dev-market.tistory.com/"

# About Section
about_profile_image: images/profile.jpg
about_content: |
  금융 VAN사에서 **50여 개의 금융기관과 200여 개 기업 고객을 연계**하고, **월 5천만 건 규모의 펌뱅킹 배치 시스템**을 개발, 운영하고 있는 서버 개발자 박재우입니다.

    **금융결제원 CMS**를 비롯해 **펌뱅킹 자동이체 업무**에 강점이 있으며, **일괄 배치 기반 펌뱅킹 시스템**, **전문 기반 TCP/IP 소켓 프로그래밍** 전반에 걸쳐 깊은 이해와 실무 경험을 보유하고 있습니다.

  현재는 **확장성, 안정성, 유지보수성**을 높이기 위해 **레거시 프로세스를 고도화하는 데 주력**하고 있습니다.


# 본문 섹션
content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: 쿠콘
        sub_title: |
            Server Developer<br>
            <a href="https://www.coocon.net/corp.act" target="_blank" rel="noopener">https://www.coocon.net/</a>
        caption: 2024.04 ~ 현재
        description: |
          - 펌뱅킹 배치 시스템 출금동의, 입금이체, 출금이체 **약 월 5천만 건** 운영
          - **[레거시 개선]**
            - **파일 송수신 공통 모듈 개발 (금융결제원 EDI, 금융결제원 CMS 방식)**<br>
              금융기관에 따라 상이했던 전문 레이아웃에 의해 기존 100여개로 분리되었던 송수신 프로세스를 공통 모듈로 개발 -> 패턴 기반 프로세스 설계로 객체 기반 오류 처리 패턴, 추상화 계층 패턴 등을 활용하여 확장성, 안정성, 유지보수성 고도화
            - **파일 송수신 모니터링 시스템 이관**<br>
              기존 문자로 수신되던 모니터링 시스템을 협업툴 등록 자동화로 이관 -> 길이 제한(80byte), 불필요한 비용 발생(약 월 100만원의 비용), 폴링 기반 공백(20분 주기) 개선
          - **[자동화]**
            - **결과파일 대응답 모듈 개발**<br>
              기존 수기처리로 진행되던 UAT 지원 -> 결과처리 자동화 모듈 구현으로 UAT 기간 50% 단축
            - **금융결제원 출금이체 변경접수 요청(FB0211) 프로세스 개선**<br>
              기존 수기처리로 진행되던 금융결제원 출금이체 변경접수요청 누락건에 대한 대응답 -> 기타오류 대응답 자동화 로직 구현하여 운영 비용 90% 절감

  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: 금융결제원 EDI 송수신 공통 모듈 개발
        #link: "https://dev-market.tistory.com/entry/2-%EC%A0%95%ED%99%95%ED%95%9C-%EC%A0%95%EB%B3%B4%EB%A5%BC-%EC%A6%89%EC%8B%9C-%EA%B7%B8%EB%A6%AC%EA%B3%A0-%EB%82%AE%EC%9D%80-%EC%A7%80%EC%97%B0%EC%9C%A8%EB%A1%9C"
        #link_text: "[4] 각기 다른 100여개의 송수신 프로세스, 공통 모듈로 탄생시킬 수는 없을까?"
        caption: 2025.07 -
        quote: >
          객체 기반 오류 처리 패턴과 추상화 계층 패턴 활용, MTTR 전 분기 대비 50% 개선, Client Onboarding Time 4주 -> 1주로 단축
        description: |
          description: |
            금융결제원 EDI 송수신 프로세스 100여 개를 분석하여 공통부 규격을 재정의하고 추상화 계층을 도입, 분산된 로직을 하나의 공통 모듈로 통합해 코드 라인을 총합 20만 줄에서 3천 줄로 축소했습니다.<br>
            객체 기반 오류 처리 패턴 적용으로 MTTR을 전 분기 대비 50% 개선했으며, 신규 기관 연동 시 중복 구현 없이 모듈 재사용만으로 Client Onboarding Time을 4주에서 1주로 단축했습니다.

          
      - layout: top-middle
        title: 파일 송수신 알림 시스템 이관 (문자 -> 협업툴 등록)
        link: "https://dev-market.tistory.com/entry/%EB%AA%A8%EB%8B%88%ED%84%B0%EB%A7%81-%EC%95%8C%EB%A6%BC-%EB%AC%B8%EC%9E%90-%EC%88%98%EC%8B%A0%EC%97%90%EC%84%9C-%ED%98%91%EC%97%85%ED%88%B4-%EB%93%B1%EB%A1%9D%EC%9C%BC%EB%A1%9C-1"
        link_text: "[1] 모니터링 알림, 문자 수신에서 협업툴 등록으로"
        caption: 2025.05 - 2025.07
        quote: >
          문자 알림 대비 협업툴 알림 전환으로 건당 비용 제거, 운영 반영 후 알림 누락률 0%, 폴링 방식 제거와 이벤트 기반 등록 도입, 지연 시간 40ms → 15ms 단축
        description: |
            문자 알림 기반 모니터링은 건당 비용이 들고 정보도 제한적이었으며, 20분 주기 확인으로 공백이 생기는 문제가 있었습니다.<br>
            협업툴 알림으로 전환해 월 100만원의 비용을 없앴고, 운영 반영 후 지금까지 알림 누락률 0%를 유지하고 있습니다.<br>
            또한 기존 20분 간격의 폴링 방식을 Active-Active로 구성된 AP 서버에서 메시지큐 컨슈머로 분기 처리해 이벤트 기반 등록을 구현했습니다.<br>
            원장 및 내역 테이블을 다중 JOIN하던 쿼리를 WITH절 기반 동적 쿼리로 전환하여 평균 지연 시간을 40ms에서 15ms로 줄였습니다.


  - title: Education
    layout: list
    content:
      - layout: left
        title: 세종대학교
        sub_title: 소프트웨어학과
        caption: 2019.03 - 2024.02
        description: |
          -

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
