# Site
url: "https://jaewoopk.github.io"
baseurl: ""
repository: "jaewoopk/jaewoopk.github.io"
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 박재우
title: Server Developer (Finance IT)
email: jaewoopk000@naver.com
website: https://github.com/jaewoopk

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  jaewoopk

# Additional icon links
additional_links:
  - title: Blog (Tistory)
    icon: fas fa-blog
    url: "https://dev-market.tistory.com/"

# About Section
about_profile_image: images/profile.jpg
about_content: |
  금융 VAN사에서 **50여 개의 금융기관과 200여 개 기업 고객을 연계**하고, **월 5천만 건 규모의 펌뱅킹 배치 시스템**을 개발, 운영하고 있는 서버 개발자 박재우입니다.

    **금융결제원 CMS**를 비롯해 **펌뱅킹 자동이체 업무**에 강점이 있으며, **일괄 배치 기반 펌뱅킹 시스템**, **전문 기반 TCP/IP 소켓 프로그래밍** 전반에 걸쳐 깊은 이해와 실무 경험을 보유하고 있습니다.

  현재는 **확장성, 안정성, 유지보수성**을 높이기 위해 **레거시 프로세스를 고도화하는 데 주력**하고 있습니다.


# 본문 섹션
content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: 쿠콘
        sub_title: |
            <a href="https://www.coocon.net/corp.act" target="_blank" rel="noopener">https://www.coocon.net/</a><br>
            Server Developer
        caption: 2024.04 ~ 현재
        description: |
          - 펌뱅킹 배치 시스템 출금동의, 입금이체, 출금이체 **약 월 5천만 건** 운영
          - **[레거시 개선]**
            - **파일 송수신 공통 모듈 개발(금융결제원 EDI, 금융결제원 CMS 방식)**<br>
              금융기관에 따라 상이했던 전문 레이아웃에 의해 기존 100여개로 분리되었던 송수신 프로세스를. 공통. 모듈로. 개발 -> 패턴 기반 프로세스 설계로 객체 기반 오류 처리 패턴, 추상화. 계층. 패턴. 등을. 활용하여 확장성, 안정성, 유지보수성 고도화
            - **파일 송수신 모니터링 시스템 이관**<br>
              기존 문자로 수신되던 모니터링 시스템을 협업툴 등록 자동화로 이관 -> 길이 제한(80byte), 불필요한 비용 발생(약 월 100만원의 비용), 폴링 기반 공백(20분 주기) 제거
          - **[자동화]**
            - 결과파일 대응답 모듈 개발<br>
              기존 수기처리로 진행되던 UAT 지원 -> 결과처리 자동화 모듈 구현으로 UAT 기간 50% 단축
            - 금융결제원 출금이체 변경접수 요청 개선<br>
              기존 수기처리로 진행되던 금융결제원 출금이체 변경접수요청 누락건에 대한 대응답 -> 기타오류 대응답 자동화 로직 구현하여 운영 비용 절감

  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: 금융결제원 EDI 송수신 공통 모듈 개발 (레거시 개선)
        link: "https://dev-market.tistory.com/entry/2-%EC%A0%95%ED%99%95%ED%95%9C-%EC%A0%95%EB%B3%B4%EB%A5%BC-%EC%A6%89%EC%8B%9C-%EA%B7%B8%EB%A6%AC%EA%B3%A0-%EB%82%AE%EC%9D%80-%EC%A7%80%EC%97%B0%EC%9C%A8%EB%A1%9C"
        link_text: "[4] 각기 다른 100여개의 송수신 프로세스, 공통 모듈로 탄생시킬 수는 없을까?"
        additional_links:
          - title: Blog (Tistory)
            icon: fas fa-blog
            url: "https://dev-market.tistory.com/entry/2-%EC%A0%95%ED%99%95%ED%95%9C-%EC%A0%95%EB%B3%B4%EB%A5%BC-%EC%A6%89%EC%8B%9C-%EA%B7%B8%EB%A6%AC%EA%B3%A0-%EB%82%AE%EC%9D%80-%EC%A7%80%EC%97%B0%EC%9C%A8%EB%A1%9C"
        caption: 2025.07 -
        quote: >
          Adpater 패턴과 은행 별 cfg파일 분리, Jenkins 파이프라인으로 공통 모듈 개발
        description: |
          레거시 C/Pro*C 기반 배치를 메타데이터·DTO 기반으로 전환하며 공통화, 유지보수성, 성능을 개선했습니다.
          
      - layout: top-middle
        title: 파일 송수신 알림 시스템 이관 (문자 -> 협업툴 등록)
        link: "https://dev-market.tistory.com/entry/%EB%AA%A8%EB%8B%88%ED%84%B0%EB%A7%81-%EC%95%8C%EB%A6%BC-%EB%AC%B8%EC%9E%90-%EC%88%98%EC%8B%A0%EC%97%90%EC%84%9C-%ED%98%91%EC%97%85%ED%88%B4-%EB%93%B1%EB%A1%9D%EC%9C%BC%EB%A1%9C-1"
        link_text: "[1] 모니터링 알림, 문자 수신에서 협업툴 등록으로"
        additional_links:
          - title: Blog (Tistory)
            icon: fas fa-blog
            url: "https://dev-market.tistory.com/entry/%EB%AA%A8%EB%8B%88%ED%84%B0%EB%A7%81-%EC%95%8C%EB%A6%BC-%EB%AC%B8%EC%9E%90-%EC%88%98%EC%8B%A0%EC%97%90%EC%84%9C-%ED%98%91%EC%97%85%ED%88%B4-%EB%93%B1%EB%A1%9D%EC%9C%BC%EB%A1%9C-1"
        caption: 2025.05 - 2025.07
        quote: >
          Adpater 패턴과 은행 별 cfg파일 분리, Jenkins 파이프라인으로 공통 모듈 개발
        description: |
          레거시 C/Pro*C 기반 배치를 메타데이터·DTO 기반으로 전환하며 공통화, 유지보수성, 성능을 개선했습니다.

  - title: Education
    layout: list
    content:
      - layout: left
        title: 세종대학교
        sub_title: 소프트웨어학과
        caption: 2019.03 - 2024.02
        description: |
          -

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
