# Site
url: "https://jaewoopk.github.io"
baseurl: ""                         # 유저 페이지는 빈 값
repository: "jaewoopk/jaewoopk.github.io"
#favicon: images/favicon.ico         # 실제 파일 있으면 유지, 없으면 주석 처리

# Content configuration version
version: 2

# Personal info (당신 정보로 교체)
name: 박재우
title: Backend Engineer (Finance IT)
email: jaewoopk000@naver.com
website: https://github.com/jaewoopk

# Dark Mode (true/false/never)
darkmode: true

# Social links (당신 계정으로 수정)
github_username:  jaewoopk
linkedin_username: your-linkedin
instagram_username: your-instagram
# 필요 없는 항목은 지워도 됩니다

# Additional icon links (불필요 키 제거)
additional_links:
  - title: Blog (Tistory)
    icon: fas fa-blog
    url: "https://jaewoopk.github.io"   # 원하면 다른 링크로

# About Section
#about_profile_image: images/profile.jpg  # 실제 파일 넣기
about_content: |
  안녕하세요. 금융권 배치/OLTP 시스템을 개발·운영하며 레거시 고도화와 성능/안정성 개선에 집중하고 있습니다.
  C/Pro*C, Oracle, Unix/Linux 기반에서 Spring Batch로의 전환을 주도하고 있습니다.

  가장 자신 있는 분야는 <mark>펌뱅킹 배치</mark>, <mark>파일→DB→파일</mark> 파이프라인 고도화입니다.

# 본문 섹션(원하는 대로 정리)
content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: minibank 프로젝트
        link: https://github.com/jaewoopk/minibank
        additional_links:
          - title: GitHub
            icon: fab fa-github
            url: https://github.com/jaewoopk/minibank
        quote: >
          Spring Boot + Spring Batch로 File→DB→File 파이프라인 시뮬레이터
        description: |
          레거시 C/Pro*C 기반 배치를 메타데이터·DTO 기반으로 전환하며 공통화, 유지보수성, 성능을 개선했습니다.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: (회사명)
        sub_title: Backend/Batch Developer
        caption: 20XX.XX - Present
        description: |
          - 펌뱅킹 자동이체 공통모듈화, 신규 업체 연동 1주 → 1일
          - 장애 월 5건 → 1건 이하, 처리속도 2배 개선 등

  - title: Education
    layout: list
    content:
      - layout: left
        title: (학교명)
        sub_title: (전공)
        caption: YYYY - YYYY
        description: |
          관련 과목, 프로젝트 간단 요약

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
